### ISSUE TITLE
Make it clearer where to get the client id and client secret for Speech APIs

### ISSUE THREAD

**Issue by wadewegner** [Microsoft/ProjectOxford-ClientSDK#1]
Details are buried in different places. The Python sample says to use the subscription key for client secret, but didn't see that in the C# docs. All I see is go to the website to get the client id (which is the subscription key?) but I actually got access through the Azure Marketplace which uses primary and secondary keys. So, consider me very confused.

**Comment by wadewegner** [comment]
Looking at the forums, this seems to be a popular point of confusion. Here's a question from June: https://social.msdn.microsoft.com/Forums/azure/en-US/e1977f27-4360-4f28-b06c-8e0b7a2e7d46/client-id-for-project-oxford?forum=mlapi

**Comment by yungshinlintw** [comment]
Thanks a lot for reporting the confusion here. We discussed offline on this. The subscription key is the key used for signing up Project Oxford Speech API, instead of the Azure subscription key.

Here is the end to end steps for this, as of early November 2015. Hope that this helps.

- Go to http://azure.net and sign up an account.
- Go to Azure portal site.
- Click "+" at the bottom of window to add a new service
<img width="886" alt="azure_new" src="https://cloud.githubusercontent.com/assets/14239352/10897251/60a3f588-8174-11e5-92a1-b9053282c263.png">
- Select "Marketplace" to add new app service.
<img width="871" alt="azure_marketplace" src="https://cloud.githubusercontent.com/assets/14239352/10897308/cc733bde-8174-11e5-9575-b98950d1977a.png">
- In the "Choose a Developer Service" dialog, scroll and select "Speech APIs" (or Computer Vision APIs/Face APIs).
<img width="733" alt="azure_speechapis" src="https://cloud.githubusercontent.com/assets/14239352/10897332/0c37c280-8175-11e5-8a84-fe59513103e4.png">
- Follow the instruction of the dialog to review the legal terms and accept the purchase (it's free as of early November 2015)
- After the service is started, click on the arrow on Speech APIs to manage the service.
<img width="704" alt="azure_speechapisgo" src="https://cloud.githubusercontent.com/assets/14239352/10897395/d7309246-8175-11e5-90fb-217de8d299b6.png">
- This will take you to the Speech API dashboard. Click on "Manage your application and service"
<img width="723" alt="azure_speechapisdashboard" src="https://cloud.githubusercontent.com/assets/14239352/10897560/5fe9bd78-8177-11e5-8f02-dd7a95c49be3.png">
- This will show you the keys of Speech API. Click on "Show" to reveal the keys. Copy the value of Primary key as the client secret in the code. You do not need to change client ID in the code.
<img width="983" alt="azure_speechapiskeys" src="https://cloud.githubusercontent.com/assets/14239352/10897513/dfb721c2-8176-11e5-9755-438e912ae8b2.png">

**Comment by miguelarian** [comment]
Sorry but this is not clear enough. I am able to find the primary key which I can use as client secret. Where can I find the client id?

thanks.

**Comment by cthrash** [comment]
You can choose a client ID of your liking.
