### ISSUE TITLE
how to obtain a subscription key for Face API?

### ISSUE THREAD

**Issue by gaomingok** [Microsoft/ProjectOxford-ClientSDK#23]
URL-https://oxford-portal.azurewebsites.net/doc/general/subscription-key-mgmt  returns error，did it has a another way?

**Comment by lightfrenzy** [comment]
Hi, Gaomingok!

Looks like we have a broken link -- can you point me to the spot where you found that link?

In order to get a key for Face API, follow these steps:
1. Go to https://www.projectoxford.ai/Account/Login
2. Login/Sign up for a Microsoft Account
3. Click "Request new keys"
4. Select the keys of your choice and submit
5. Start coding!

**Comment by lightfrenzy** [comment]
We've tracked down all the broken links, fixed them, and redirected any remaining ones in the ether to our new website http://www.microsoft.com/cognitive. Thanks for reporting!
