### ISSUE TITLE
Do we have a WebSocket API reference for continuous Speech Recognition?

### ISSUE THREAD

**Issue by parijat1209** [Microsoft/ProjectOxford-ClientSDK#58]
Hi,

Speech.JS cannot do continuous recognition as the Partial Response is never received. I believe SpeechClient dll is connecting to Bing WebSocket servers for the continuous recognition to happen. Can't we directly connect to Bing WebSocket servers from HTML5 WebSockets? If so, then where can I find a sample code or a reference to directly connect to the Bing Speech WebSocket servers using JavaScript WebSockets?

Thanks

**Comment by dmiller235623** [comment]
connect to my outlook email not my gmail.. I get a lot of
spam...dmiller235623@outlook.com

**Comment by ochakov** [comment]
+1

**Comment by sushma-ananda** [comment]
We are looking at disable Barge-in on ASR (c#.net) module of Project Oxford Speech API. Can you please help suggest us onm this?

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Speech-STT-JavaScript#4

**Comment by williamsandstrom** [comment]
I'm also looking for this. I've looked at the request from the client SDK for Windows using Fiddler and there is web socket endpoints available there

This are what the sent headers from the library looks like

https://websockets.platform.bing.com/ws/speech/recognize

```
GET /ws/speech/recognize HTTP/1.1
Connection: Upgrade
Upgrade: Websocket
Authorization: Bearer ashdjashdjlasd
User-Agent: Mozilla/4.0 (Windows 8; Unknown;Unknown;ProcessName/AppName=Unknown;DeviceType=Near;SpeechClient=1.0.716436)
X-WebSocketConnectionId: 4eb71213ef974307826d4c89639ddf53
X-CU-LogLevel: 1
X-Search-AppID: Unknown
X-Search-Market: en-US
X-Search-UILang: en-US
Sec-WebSocket-Key: lS4KX2vWHDnmiO3UnECc8A==
Sec-WebSocket-Version: 13
Host: websockets.platform.bing.com
```

This makes things bad since I cannot add custom headers to a websocket in JS.

If you are able to add the authorization header to your websocket request, then you can use the code above. Also see their [demo](https://www.microsoft.com/cognitive-services/en-us/speech-api) which uses partial response/streaming, but it uses it's own endpoint (https://cog-web-wu.azurewebsites.net/cognitive-services/ws/speechtotextdemo?language=en-US&g_Recaptcha_Response=null&isNeedVerify=false). If we could somehow add the authorization header to a web socket, we could replace the demo endpoint with the real endpoint and have a full working partial response support in JS.
