### ISSUE TITLE
C# SDK: FaceRectangle should inherit from Rectangle

### ISSUE THREAD

**Issue by SaqibS** [Microsoft/ProjectOxford-ClientSDK#6]
I am using the C# client SDKs available from NuGet.

When using the face detection API, you get back an array of FaceRectangles. However, the Emotion Detection API requires an array of Rectangles (from the Common namespace). Both types have the same 4 fields one would expect.

These should be consolidated - either FaceDetection should return Common Rectangles, or else FaceRectangle should inherit from Rectangle. Or, just use System.Drawing.Rectangle.

**Comment by yungshinlintw** [comment]
Thanks, Saqib. I am passing this feedback to emotion team to take a look.

**Comment by cthrash** [comment]
Right now we don't have a shared type library between these APIs.  For GIT users, this is not that big of a deal since you're getting the whole tree, typically, but for NuGet users this means we'd want to restructure the Face and Emotion packages to have a common dependent package, which we can do but haven't taken the time to do yet.
System.Drawing.Rectangle is a bit of a hassle since the transport format is JSON.  A variant option is to implement a TypeConverter to go between Face/Emotion rectangle and System.Drawing.Rectangle, which may be the best way to go, from a type isolation standpoint.

**Comment by StenPetrov** [comment]
Error CS1503: Argument `#2' cannot convert `Microsoft.ProjectOxford.Face.Contract.FaceRectangle' expression to type `Microsoft.ProjectOxford.Common.Rectangle[]' (CS1503) 

Too many rectangle types, please pick or inherit

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Face-Windows#1

**Comment by margaretmz** [comment]
This issue was moved to Microsoft/Cognitive-Face-Windows#1
