### ISSUE TITLE
Speech REST API - maxnbest parameter ignored

### ISSUE THREAD

**Issue by nicolaspanel** [Microsoft/ProjectOxford-ClientSDK#79]
[optional parameter __maxnbest__](https://www.microsoft.com/cognitive-services/en-us/speech-api/documentation/API-Reference-REST/BingVoiceRecognition#optional-parameters) is always ignored. Response always contains a single result.

**Comment by lightfrenzy** [comment]
Hi @nicolaspanel:

As you can see, we recently (today!) moved our SDK packages to separate repos. As such, we want to port your issue over to the new home. Can you post this on the Speech SDK you were using to make sure the issue is tracked? Here are all the links for the Speech repo:

- [Speech-to-Text for Android](https://github.com/Microsoft/Cognitive-Speech-STT-android)
- [Speech-to-Text for iOS](https://github.com/Microsoft/cognitive-speech-stt-ios)
- [Speech-to-Text for Javascript](https://github.com/Microsoft/Cognitive-Speech-STT-JavaScript)
- [Speech-to-Text for Windows](https://github.com/Microsoft/cognitive-speech-stt-windows)
- [Text-to-Speech Sampes](https://github.com/Microsoft/cognitive-speech-tts)

Thanks!
-Allison

**Comment by nicolaspanel** [comment]
Hi @lightfrenzy,
The issue come from the REST API, not from a specific SDK. 
Is there a REPO / issue tracker for the REST API?
BR

**Comment by nicolaspanel** [comment]
Hi @lightfrenzy, could you give me the more appropriate issue tracker for the REST API?
Best regards

**Comment by lightfrenzy** [comment]
Hi @nicolaspanel. I understand now that this is a problem with the API itself. The best path forward is to post a question on StackOverflow so our engineers can work with you to figure out the problem.

To do that, please visit [https://stackoverflow.com/questions/tagged/microsoft-cognitive](https://stackoverflow.com/questions/tagged/microsoft-cognitive).

Thanks for letting us know!
-Allison

**Comment by nicolaspanel** [comment]
Done, thank you
