### ISSUE TITLE
Transport error SpeechClentStatus_LoginFaild

### ISSUE THREAD

**Issue by sohilmultani** [Microsoft/ProjectOxford-ClientSDK#90]
i have create project to translate Speech to text.
So i have download this demo and use it but it will give me error : 
 "Transport error SpeechClentStatus_LoginFaild"

I have subscrive : " Speaker Recognition - Preview " in above Link
https://www.microsoft.com/cognitive-services/en-us/subscriptions

i have give Two Keys - key1 and key2
i have set key1 in setting.plist file and execute this demo - "Use Microphone with ShortPhrase mode"
but it will give me Error : "Transport error SpeechClentStatus_LoginFaild"

also i have set Key2 in setting.plist file and execute this demo - "Use Microphone with ShortPhrase mode"
but it will give me Error : "Transport error SpeechClentStatus_LoginFaild"

i have confused  what is the "luisSubscriptionID" and "luisAppID" ?

i am not set "luisSubscriptionID" and "luisAppID" if i am any Mistake  please give me suggestion.

Please Help Me.

**Comment by lightfrenzy** [comment]
Hi @sohilmultani,

It looks like you're trying to use the Speech-to-Text sample. Can you share which one you're trying to use? A few months ago, we broke out each individual project into separate repos. You can find the new link to the repo on here: [Bing Speech SDKs](https://www.microsoft.com/cognitive-services/en-us/SDK-Sample?api=bing%20speech&author=microsoft&category=sdk). I highly suggest you move to the new repo since the code base in this repo will no longer be updated.

As far as your problem goes, it looks like you're using the wrong key. Your current key is for Speaker Recognition, an API that helps you identify who is speaking in an audio clip. You should instead request and use a key for Bing Speech - Preview.

Hope this helps!

**Comment by sohilmultani** [comment]
Thank you sir for replay,
     i have solve my problem. i have a problem because i have use* wrong
key **Speaker Recognition*. now its work perfect. Now I have *use  Bing
Speech preview key*


Thank You Sir....
